name: "\U0001F680 Feature Request"
description: Suggest an idea for this project
title: "(short issue description)"
labels: [feature-request, needs-triage]
body:

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledge
      options:
        - label: I've searched the [open issues](https://github.com/aws/aws-cli/issues) and didn't find a solution or previous request.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: |
        A description of the problem you have, e.g. "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you are proposing.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: |
        What would you suggest to change to solve the problem?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        What alternative solutions or features have you've considered?
    validations:
      required: false

  - type: input
    id: aws-cli-version
    attributes:
      label: AWS CLI version used
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System and version
    validations:
      required: true
