name: PRs against develop are not accepted, please target v2 branch

on:
  pull_request:
    branches: [ develop ]

jobs:
  cleanup:
    if: github.event.repository.fork == false
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Comment on PRs against develop
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Pull requests against the develop branch are not accepted."
